# CHIsentiment: Exploring Public Sentiments of Chicago Neighborhoods

What is the relationship between the reputation and the characteristics of a neighborhood? 
Below I explore this question in the context of Chicago, IL, using social media (Twitter) data and a dataset of socioeconomic data per neighborhood available from the City of Chicago data portal (https://data.cityofchicago.org). For this exploration, a "neighborhood" is defined as one of Chicago's 77 community areas, which are officially recognized by the City of Chicago. I model neighborhood reputation as an index summarizing the sentiment of tweets mentioning a given neighborhood (more details provided as I work my way through the question).

I proceed in the following steps:
* Set up (import modules and keys that I'll need along the way)
* Construct dataset
    * Download relevant Twitter data
    * Apply sentiment analysis to tweets
    * Generate neighborhood reputation index scores for each neighborhood
    * Put socioeconomic and Twitter data per neighborhood into one table
* Develop descriptive statistics
* Develop inferential statistics
* Conclusions

# Set up

Importing relevant modules and keys

In [3]:
import time

import pandas as pd
pd.set_option('display.max_colwidth', -1)  # this helps show as much of the tweets in the dataframes as possible

%matplotlib inline
#import matplotlib.pyplot as plt

In [ ]:
# in terminal: easy_install pip
# in terminal: pip install tweepy
# in terminal: pip install --upgrade pip [per suggestion shown inside terminal]
import tweepy

import nltk
# in command line, pip install twython 
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [7]:
# These four codes constitute your authorization to extract data from Twitter
consumer_token = 'please'
consumer_secret = 'use'
access_token = 'your'
access_token_secret = 'own'

# OAuth process, using the keys and tokens
auth = tweepy.OAuthHandler(consumer_token, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

# Creation of the actual interface, using authentication
# api = tweepy.API(auth)
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

# Construct dataset

<h3>Downloading, cleaning up, and storing Twitter data in a csv file</h3>

Dataset Criteria:   
1. list of tweets within last 6-9 days. 
  * This time range limit is set by Twitter, see https://dev.twitter.com/rest/public/search
2. tweet mentions one of Chicago's 77 community areas
  * FYI there are two Community Areas inside Chicago with "Englewood" in the name. They're located adjacent to each other. There are also "Englewood" in other states, such as NJ.
3. tweet originates within 15 miles of Chicago, IL
  * Determine this by using geocoding of tweets
  * Identify geocode for Chicago by clicking on latitude/longitude info on Chicago wikipedia page: https://en.wikipedia.org/wiki/Chicago
4. tweet is in English

In [17]:
# import table with column of community area names
SES = pd.read_csv('Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012.csv')
SES = SES.dropna()  # do this so that the last row is dropped, which shows totals for whole city
#SES
#SES.columns
SES['COMMUNITY AREA NAME']

0     Rogers Park
1     West Ridge
2     Uptown
3     Lincoln Square
4     North Center
5     Lake View
6     Lincoln Park
7     Near North Side
8     Edison Park
9     Norwood Park
10    Jefferson Park
11    Forest Glen
12    North Park
13    Albany Park
14    Portage Park
15    Irving Park
16    Dunning
17    Montclaire
18    Belmont Cragin
19    Hermosa
20    Avondale
21    Logan Square
22    Humboldt park
23    West Town
24    Austin
25    West Garfield Park
26    East Garfield Park
27    Near West Side
28    North Lawndale
29    South Lawndale
           ...
47    Calumet Heights
48    Roseland
49    Pullman
50    South Deering
51    East Side
52    West Pullman
53    Riverdale
54    Hegewisch
55    Garfield Ridge
56    Archer Heights
57    Brighton Park
58    McKinley Park
59    Bridgeport
60    New City
61    West Elsdon
62    Gage Park
63    Clearing
64    West Lawn
65    Chicago Lawn
66    West Englewood
67    Englewood
68    Greater Grand Crossing
69    Ashburn
70    Auburn Gresham
71    Beverly
72    Washington Height
73    Mount Greenwood
74    Morgan Park
75    O'Hare
76    Edgewater
Name: COMMUNITY AREA NAME, dtype: object

In [8]:
# check the status of my search request limit
api.rate_limit_status('search')

{'rate_limit_context': {'access_token': '2382930698-0eCycGIeqv4SUmOvSINQbkhnb2v9hTPDlSpcb8q'},
 'resources': {'search': {'/search/tweets': {'limit': 180,
    'remaining': 180,
    'reset': 1481679991}}}}

In [23]:
# establish lists or "buckets" into which each relevant data point is going to be appended:
community_area_name_list = []
user_screen_name_list = []
user_location_list = []  
user_followers_count_list = []
tweet_coordinates_list = []
tweet_date_time_list = [] 
tweet_content_list = [] 
tweet_num_retweet_list = [] 
tweet_num_liked_list = []

# caution, the following takes a very long time

for name in SES['COMMUNITY AREA NAME']:
    time.sleep(60)  # suspends execution of the current thread for this many seconds
    for tweet in tweepy.Cursor(api.search,
                           q = name,
                           lang = 'en', 
#                           geocode = '41.836944,-87.684722,15mi').items(10):
                           geocode = '41.836944,-87.684722,15mi').items():
        community_area_name_list.append(name.lower())
        user_screen_name_list.append(tweet.user.screen_name)
        user_location_list.append(tweet.user.location)
        user_followers_count_list.append(tweet.user.followers_count)
        tweet_coordinates_list.append(tweet.coordinates)
        tweet_date_time_list.append(tweet.created_at)
        tweet_content_list.append(tweet.text)
        tweet_num_retweet_list.append(tweet.retweet_count)
        tweet_num_liked_list.append(tweet.favorite_count)

df = pd.DataFrame({
        "Community Area Mentioned": community_area_name_list,
        "User Screen Name": user_screen_name_list,
        "User Location": user_location_list,
        "User Number of Followers":user_followers_count_list,
        "Tweet Coordinates": tweet_coordinates_list,
        "Tweet Day and Time": tweet_date_time_list,
        "Tweet Number of Times Retweeted": tweet_num_retweet_list,
        "Tweet Number of Times Liked": tweet_num_liked_list,
        "Tweet Content": tweet_content_list})

Rate limit reached. Sleeping for: 724
Rate limit reached. Sleeping for: 580
Rate limit reached. Sleeping for: 634
Rate limit reached. Sleeping for: 714
Rate limit reached. Sleeping for: 712
Rate limit reached. Sleeping for: 557
Rate limit reached. Sleeping for: 634

In [26]:
df.shape
#df[0:3]
#df.to_csv('df_raw_data.csv')

(18158, 9)

<h3>Applying sentiment analysis to tweets</h3>

In [43]:
df = pd.read_csv('df_raw_data.csv')
df.columns

Index(['Unnamed: 0', 'Community Area Mentioned', 'Tweet Content',
       'Tweet Coordinates', 'Tweet Day and Time',
       'Tweet Number of Times Liked', 'Tweet Number of Times Retweeted',
       'User Location', 'User Number of Followers', 'User Screen Name'],
      dtype='object')

In [44]:
analyzer = SentimentIntensityAnalyzer()
df["Sentiment"] = df['Tweet Content'].apply(lambda tweet: analyzer.polarity_scores(tweet))

In [45]:
df[0:1]

,Unnamed: 0,Community Area Mentioned,Tweet Content,Tweet Coordinates,Tweet Day and Time,Tweet Number of Times Liked,Tweet Number of Times Retweeted,User Location,User Number of Followers,User Screen Name,Sentiment
0,0.0,rogers park,RT @ChiTribBiz: This Rogers Park building is the latest to attract investor attention as the neighborhood undergoes “a renaissance” https:/…,NaN,2016-12-13 18:48:38,0.0,2.0,NaN,443.0,giovannibacci36,"{'neu': 0.884, 'compound': 0.3612, 'pos': 0.116, 'neg': 0.0}"

In [46]:
df.Sentiment[0]
#df['Sentiment'][0]

# The following examples demonstrate the value of the compound score:
# VADER is smart, handsome, and funny. {'neg': 0.0, 'neu': 0.254, 'pos': 0.746, 'compound': 0.8316} 
# VADER is smart, handsome, and funny! {'neg': 0.0, 'neu': 0.248, 'pos': 0.752, 'compound': 0.8439} 
# VADER is very smart, handsome, and funny. {'neg': 0.0, 'neu': 0.299, 'pos': 0.701, 'compound': 0.8545} 
# VADER is VERY SMART, handsome, and FUNNY. {'neg': 0.0, 'neu': 0.246, 'pos': 0.754, 'compound': 0.9227} 
# VADER is VERY SMART, handsome, and FUNNY!!! {'neg': 0.0, 'neu': 0.233, 'pos': 0.767, 'compound': 0.9342} 
# VADER is VERY SMART, really handsome, and INCREDIBLY FUNNY!!! {'neg': 0.0, 'neu': 0.294, 'pos': 0.706, 'compound': 0.9469}

{'compound': 0.3612, 'neg': 0.0, 'neu': 0.884, 'pos': 0.116}

In [47]:
# prepare sentiment score for putting into a column of its own

# print(type(df['Sentiment'][0]))
type(df.Sentiment[0])

dict

In [48]:
# convert to string
#df['Sentiment'] = df['Sentiment'].apply(str)
df.Sentiment = df.Sentiment.apply(str)

type(df.Sentiment[0])

str

In [49]:
# now extract sentiment compound scores as additional column

df_temp = df.Sentiment.str.split(',').apply(pd.Series)
#df_temp[0:5]
df_temp[1][0:5]

0     'compound': 0.3612
1     'compound': 0.3612
2     'compound': 0.34
3     'compound': 0.5574
4     'compound': 0.5574
Name: 1, dtype: object

In [50]:
left_split = df_temp[1].str.split(': ').apply(pd.Series)
#left_split[1][0:5]
compound = left_split[1].apply(float)
df['Compound Sentiment Score'] = compound

In [52]:
#df[0:5]
df.to_csv('df_wCompound.csv')

<h3>Generating neighborhood reputation index scores for each neighborhood</h3>

In [41]:
df = pd.read_csv('df_wCompound.csv')
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Community Area Mentioned',
       'Tweet Content', 'Tweet Coordinates', 'Tweet Day and Time',
       'Tweet Number of Times Liked', 'Tweet Number of Times Retweeted',
       'User Location', 'User Number of Followers', 'User Screen Name',
       'Sentiment', 'Compound Sentiment Score'],
      dtype='object')

In [42]:
del df['Unnamed: 0']
del df['Unnamed: 0.1']
df['Count 1'] = 1
df.shape

(18159, 12)

In [43]:
#df[0:5]

I assume that reputation entails both a sentiment (positive, negative) and its diffusion. Therefore I will compute a neighborhood reputation index using the sentiment data, as well as information on the number of "likes" and "retweets" for each tweet and followers for the author of each tweet.

In [44]:
# I begin by computing the diffusion of each tweet.
# I assume that likers, retweeters, and followers do not overlap although in reality they likely do.

# diffusion to passive readers (Followers)
df['User to Follower Diffusion'] = df['Compound Sentiment Score']*df['User Number of Followers']

# diffusion to more active readers, demonstrated by liking a tweet
df['User to Liker Diffusion'] = df['Compound Sentiment Score']*df['Tweet Number of Times Liked']

# diffusion to even more active readers, demonstrated by retweeting a tweet
df['User to Retweeter Diffusion'] = df['Compound Sentiment Score']*df['Tweet Number of Times Retweeted']

# total diffusion
df['Tweet Total Diffusion'] = df['User to Follower Diffusion'] + df['User to Liker Diffusion'] + df['User to Retweeter Diffusion']

In [45]:
# Now I establish the number of positive vs. negative sentiment tweets per neighborhood. 

tweet_by_neighb = df.groupby('Community Area Mentioned')

# total number of positive tweets per neighborhood:
total_tweet_by_neighb_pos_num = tweet_by_neighb.apply(lambda x: x[x['Compound Sentiment Score'] > 0]['Count 1'].sum())
# total number of negative tweets per neighborhood:
total_tweet_by_neighb_neg_num = tweet_by_neighb.apply(lambda x: x[x['Compound Sentiment Score'] < 0]['Count 1'].sum())
# total number of positive and negative tweets per neighborhood:
total_tweet_by_neighb_num = total_tweet_by_neighb_pos_num + total_tweet_by_neighb_neg_num

In [46]:
# Now I compute summary measures of the sentiment component of a neighborhood's reputation.
# Because I assume that a reputation involves a positive or negative sentiment, 
# I exclude all tweets that score as neutral (compound score = 0, review usign df[df['Compound Sentiment Score'] == 0]).

tweet_by_neighb = df.groupby('Community Area Mentioned')

for neighborhood in tweet_by_neighb:
    sum_pos_tweet_by_neighb = tweet_by_neighb.apply(lambda x: x[x['Compound Sentiment Score'] > 0]['Compound Sentiment Score'].sum())
    sum_neg_tweet_by_neighb = tweet_by_neighb.apply(lambda x: x[x['Compound Sentiment Score'] < 0]['Compound Sentiment Score'].sum())

In [47]:
neighb_level_df = pd.DataFrame({'Total Number of Positive Tweets':total_tweet_by_neighb_pos_num,
                                'Total Number of Negative Tweets':total_tweet_by_neighb_neg_num,
                                'Total Number of Positive and Negative Tweets': total_tweet_by_neighb_num,
                                'Sum Positive Tweet Sentiment':sum_pos_tweet_by_neighb,
                                'Sum Negative Tweet Sentiment':sum_neg_tweet_by_neighb})

In [48]:
neighb_level_df = neighb_level_df.drop(neighb_level_df.index[[0]])  # removes one row with no community area name

In [49]:
neighb_level_df

,Sum Negative Tweet Sentiment,Sum Positive Tweet Sentiment,Total Number of Negative Tweets,Total Number of Positive Tweets,Total Number of Positive and Negative Tweets
Community Area Mentioned,,,,,
albany park,-5.6676,9.7646,16,18,34
archer heights,0.0000,0.5574,0,1,1
ashburn,-10.6303,5.5188,28,15,43
auburn gresham,-5.9133,1.1233,17,2,19
austin,-14.1287,18.5554,34,36,70
avalon park,0.0000,0.0000,0,0,0
avondale,-7.2062,7.6270,18,15,33
belmont cragin,0.0000,0.0000,0,0,0
beverly,-35.3824,174.6288,115,344,459
bridgeport,-16.1919,44.0589,36,87,123
brighton park,-0.5216,2.0169,1,3,4
burnside,-3.4787,1.1148,5,2,7
chatham,-72.7402,14.6224,114,27,141
chicago lawn,-7.2072,5.9058,12,19,31
clearing,-33.5426,61.5269,65,131,196
douglas,-44.9209,152.1378,87,264,351
dunning,-8.8078,22.1743,21,65,86
east garfield park,-159.6528,5.5437,287,11,298
east side,-9.8968,23.0107,24,45,69
edgewater,-15.7117,37.0392,42,74,116
edison park,-0.5958,8.7805,2,17,19
englewood,-178.2184,119.3052,362,238,600
forest glen,-0.5574,0.9058,1,1,2
fuller park,0.0000,0.0000,0,0,0
gage park,-0.3818,2.5715,1,4,5
garfield ridge,-25.9085,2.9174,40,5,45
grand boulevard,0.0000,4.7700,0,10,10
greater grand crossing,0.0000,8.1600,0,12,12
hegewisch,0.0000,0.5106,0,1,1
hermosa,-10.6583,24.3991,22,58,80
...,...,...,...,...,...
montclaire,0.0000,0.0000,0,0,0
morgan park,-36.5963,108.6903,103,200,303
mount greenwood,-15.6672,6.5758,25,14,39
near north side,-0.8020,7.8572,1,16,17
near south side,0.0000,3.9044,0,8,8
near west side,-4.9914,12.8581,19,29,48
new city,-68.2218,106.1651,120,224,344
north center,-10.4607,18.5448,21,40,61
north lawndale,-54.1112,57.0527,112,101,213
north park,-14.5291,38.2856,36,74,110
norwood park,-7.7546,4.1417,21,7,28
o'hare,-0.4466,2.5444,1,5,6
oakland,-18.7194,6.1594,32,22,54
portage park,-10.4311,15.3506,19,25,44
pullman,-6.3766,9.2418,14,17,31
riverdale,-134.1097,8.7716,210,20,230
rogers park,-8.3172,92.8450,25,168,193
roseland,-162.5234,12.9962,315,30,345
south chicago,-144.9457,132.6081,283,266,549
south deering,0.0000,0.5848,0,1,1
south shore,-26.3318,38.3309,68,86,154
uptown,-57.6967,95.4810,147,236,383
washington park,0.0000,0.5994,0,1,1
west englewood,-18.0989,1.0187,32,2,34
west garfield park,-5.0693,4.6487,7,8,15
west lawn,-1.6820,1.2250,6,4,10
west pullman,-4.0916,3.1795,10,6,16
west ridge,-4.8305,14.4780,7,24,31
west town,-2.3882,25.6804,4,50,54
woodlawn,-3.2651,26.1762,10,47,57

<h4>Computing weighted and evenly weighed reputation scores per neighborhood</h4>

<u>Evenly Weighed Reputation Score:</u> Average is computed evenly, assuming a positive tweet is equal in influence as a negative tweet (except for direction of opinion)

<u>Weighted Reputation Score:</u> Humans have a famous bias for the negative - "even when of equal intensity, things of a more negative nature (e.g. unpleasant thoughts, emotions, or social interactions; harmful/traumatic events) have a greater effect on one's psychological state and processes than do neutral or positive things" (https://en.wikipedia.org/wiki/Negativity_bias). 

To model this negativity bias, I consider a ratio from an HBR article (Folkman, Jack Zenger and Joseph. 2013. “The Ideal Praise-to-Criticism Ratio.” Harvard Business Review. March 15. https://hbr.org/2013/03/the-ideal-praise-to-criticism.), which suggests that the ideal praise-to-criticism ratio in the context of team performance assessments is as follows: 5 positive comments for every negative one. Based on this idea, the weighted reputation score calculation below pretends that there are five times as many negative tweets for every neighborhood.

In [51]:
for neighborhood in neighb_level_df:
    avg_neg = sum_neg_tweet_by_neighb / total_tweet_by_neighb_neg_num
    avg_pos = sum_pos_tweet_by_neighb / total_tweet_by_neighb_pos_num
    reputation_index_1 = (avg_neg+avg_pos) / 2
    reputation_index_2 = ((5*avg_neg)+avg_pos) / 6
    
neighb_level_df['Average Negative Sentiment'] = avg_neg
neighb_level_df['Average Positive Sentiment'] = avg_pos
neighb_level_df['Unweighted Reputation Score'] = reputation_index_1
neighb_level_df['Weighted Reputation Score'] = reputation_index_2

In [52]:
neighb_level_df.fillna(0, inplace=True)
neighb_level_df.sort_values(by='Unweighted Reputation Score')

,Sum Negative Tweet Sentiment,Sum Positive Tweet Sentiment,Total Number of Negative Tweets,Total Number of Positive Tweets,Total Number of Positive and Negative Tweets,Average Negative Sentiment,Average Positive Sentiment,Unweighted Reputation Score,Weighted Reputation Score
Community Area Mentioned,,,,,,,,,
near north side,-0.8020,7.8572,1,16,17,-0.802000,0.491075,-0.155463,-0.586487
oakland,-18.7194,6.1594,32,22,54,-0.584981,0.279973,-0.152504,-0.440822
chicago lawn,-7.2072,5.9058,12,19,31,-0.600600,0.310832,-0.144884,-0.448695
riverdale,-134.1097,8.7716,210,20,230,-0.638618,0.438580,-0.100019,-0.459085
mount greenwood,-15.6672,6.5758,25,14,39,-0.626688,0.469700,-0.078494,-0.443957
west garfield park,-5.0693,4.6487,7,8,15,-0.724186,0.581088,-0.071549,-0.506640
burnside,-3.4787,1.1148,5,2,7,-0.695740,0.557400,-0.069170,-0.486883
hyde park,-79.1596,124.0035,122,239,361,-0.648849,0.518843,-0.065003,-0.454234
chatham,-72.7402,14.6224,114,27,141,-0.638072,0.541570,-0.048251,-0.441465
new city,-68.2218,106.1651,120,224,344,-0.568515,0.473951,-0.047282,-0.394771
west ridge,-4.8305,14.4780,7,24,31,-0.690071,0.603250,-0.043411,-0.474518
west town,-2.3882,25.6804,4,50,54,-0.597050,0.513608,-0.041721,-0.411940
roseland,-162.5234,12.9962,315,30,345,-0.515947,0.433207,-0.041370,-0.357755
dunning,-8.8078,22.1743,21,65,86,-0.419419,0.341143,-0.039138,-0.292659
garfield ridge,-25.9085,2.9174,40,5,45,-0.647713,0.583480,-0.032116,-0.442514
hermosa,-10.6583,24.3991,22,58,80,-0.484468,0.420674,-0.031897,-0.333611
west englewood,-18.0989,1.0187,32,2,34,-0.565591,0.509350,-0.028120,-0.386434
east garfield park,-159.6528,5.5437,287,11,298,-0.556282,0.503973,-0.026154,-0.379572
clearing,-33.5426,61.5269,65,131,196,-0.516040,0.469671,-0.023185,-0.351755
north center,-10.4607,18.5448,21,40,61,-0.498129,0.463620,-0.017254,-0.337837
south chicago,-144.9457,132.6081,283,266,549,-0.512176,0.498527,-0.006824,-0.343725
ashburn,-10.6303,5.5188,28,15,43,-0.379654,0.367920,-0.005867,-0.255058
montclaire,0.0000,0.0000,0,0,0,0.000000,0.000000,0.000000,0.000000
avalon park,0.0000,0.0000,0,0,0,0.000000,0.000000,0.000000,0.000000
washington park,0.0000,0.5994,0,1,1,0.000000,0.599400,0.000000,0.000000
hegewisch,0.0000,0.5106,0,1,1,0.000000,0.510600,0.000000,0.000000
greater grand crossing,0.0000,8.1600,0,12,12,0.000000,0.680000,0.000000,0.000000
near south side,0.0000,3.9044,0,8,8,0.000000,0.488050,0.000000,0.000000
fuller park,0.0000,0.0000,0,0,0,0.000000,0.000000,0.000000,0.000000
south deering,0.0000,0.5848,0,1,1,0.000000,0.584800,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
south shore,-26.3318,38.3309,68,86,154,-0.387232,0.445708,0.029238,-0.248409
douglas,-44.9209,152.1378,87,264,351,-0.516332,0.576280,0.029974,-0.334230
o'hare,-0.4466,2.5444,1,5,6,-0.446600,0.508880,0.031140,-0.287353
portage park,-10.4311,15.3506,19,25,44,-0.549005,0.614024,0.032509,-0.355167
north lawndale,-54.1112,57.0527,112,101,213,-0.483136,0.564878,0.040871,-0.308467
pullman,-6.3766,9.2418,14,17,31,-0.455471,0.543635,0.044082,-0.288954
east side,-9.8968,23.0107,24,45,69,-0.412367,0.511349,0.049491,-0.258414
austin,-14.1287,18.5554,34,36,70,-0.415550,0.515428,0.049939,-0.260387
loop,-155.8448,330.7517,407,677,1084,-0.382911,0.488555,0.052822,-0.237667
avondale,-7.2062,7.6270,18,15,33,-0.400344,0.508467,0.054061,-0.248876
irving park,-8.3567,9.9079,23,21,44,-0.363335,0.471805,0.054235,-0.224145
north park,-14.5291,38.2856,36,74,110,-0.403586,0.517373,0.056893,-0.250093
west pullman,-4.0916,3.1795,10,6,16,-0.409160,0.529917,0.060378,-0.252647
edgewater,-15.7117,37.0392,42,74,116,-0.374088,0.500530,0.063221,-0.228318
lake view,-6.6750,16.2563,15,28,43,-0.445000,0.580582,0.067791,-0.274070
brighton park,-0.5216,2.0169,1,3,4,-0.521600,0.672300,0.075350,-0.322617
near west side,-4.9914,12.8581,19,29,48,-0.262705,0.443383,0.090339,-0.145024
morgan park,-36.5963,108.6903,103,200,303,-0.355304,0.543451,0.094074,-0.205511
albany park,-5.6676,9.7646,16,18,34,-0.354225,0.542478,0.094126,-0.204775
beverly,-35.3824,174.6288,115,344,459,-0.307673,0.507642,0.099984,-0.171787
lower west side,-0.2960,0.5093,1,1,2,-0.296000,0.509300,0.106650,-0.161783
auburn gresham,-5.9133,1.1233,17,2,19,-0.347841,0.561650,0.106904,-0.196259
edison park,-0.5958,8.7805,2,17,19,-0.297900,0.516500,0.109300,-0.162167
rogers park,-8.3172,92.8450,25,168,193,-0.332688,0.552649,0.109980,-0.185132
norwood park,-7.7546,4.1417,21,7,28,-0.369267,0.591671,0.111202,-0.209110
lincoln square,-2.3563,88.3560,7,157,164,-0.336614,0.562777,0.113081,-0.186716
woodlawn,-3.2651,26.1762,10,47,57,-0.326510,0.556940,0.115215,-0.179268
gage park,-0.3818,2.5715,1,4,5,-0.381800,0.642875,0.130538,-0.211021
humboldt park,-27.2708,22.3413,126,45,171,-0.216435,0.496473,0.140019,-0.097617
forest glen,-0.5574,0.9058,1,1,2,-0.557400,0.905800,0.174200,-0.313533

In [54]:
neighb_level_df.shape
neighb_level_df.to_csv('df_neighb_level.csv')

<h3>Putting socioeconomic and Twitter data per neighborhood into one table</h3>

In [55]:
df_neighb_level = pd.read_csv('df_neighb_level.csv')
df_SES = pd.read_csv('Census_Data_-_Selected_socioeconomic_indicators_in_Chicago__2008___2012.csv')
df_SES = df_SES.dropna()  # do this so that the last row is dropped, which totals for the whole city

In [56]:
print(df_neighb_level.shape)
print(df_SES.shape)
# neighborhood level df appears to be missing some community areas, assume that it's bc these were not mentioned in tweets

(72, 10)
(77, 9)

In [57]:
# prepare for merging the two dataframes on df_SES['COMMUNITY AREA NAME'] and df_neighb_level['Community Area Mentioned']
df_SES = df_SES.sort_values(by='COMMUNITY AREA NAME')  # assure both columns are sorted in same direction
df_SES['COMMUNITY AREA NAME'] = df_SES['COMMUNITY AREA NAME'].apply(lambda x: x.lower())  # assure both are in lowercase
df_neighb_level.columns.values[0] ='COMMUNITY AREA NAME'  # assure both columns are named the same

In [58]:
print(df_neighb_level.columns)
print(df_SES.columns)

Index(['COMMUNITY AREA NAME', 'Sum Negative Tweet Sentiment',
       'Sum Positive Tweet Sentiment', 'Total Number of Negative Tweets',
       'Total Number of Positive Tweets',
       'Total Number of Positive and Negative Tweets',
       'Average Negative Sentiment', 'Average Positive Sentiment',
       'Unweighted Reputation Score', 'Weighted Reputation Score'],
      dtype='object')
Index(['Community Area Number', 'COMMUNITY AREA NAME',
       'PERCENT OF HOUSING CROWDED', 'PERCENT HOUSEHOLDS BELOW POVERTY',
       'PERCENT AGED 16+ UNEMPLOYED',
       'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA',
       'PERCENT AGED UNDER 18 OR OVER 64', 'PER CAPITA INCOME ',
       'HARDSHIP INDEX'],
      dtype='object')

In [59]:
df_merged = df_SES.merge(df_neighb_level, 
                         how='left', 
                         on='COMMUNITY AREA NAME')
df_merged = df_merged.sort_values(by='Community Area Number')
df_merged = df_merged.fillna('NA')
df_merged

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX,Sum Negative Tweet Sentiment,Sum Positive Tweet Sentiment,Total Number of Negative Tweets,Total Number of Positive Tweets,Total Number of Positive and Negative Tweets,Average Negative Sentiment,Average Positive Sentiment,Unweighted Reputation Score,Weighted Reputation Score
60,1.0,rogers park,7.7,23.6,8.7,18.2,27.5,23939,39.0,-8.3172,92.845,25,168,193,-0.332688,0.552649,0.10998,-0.185132
74,2.0,west ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0,-4.8305,14.478,7,24,31,-0.690071,0.60325,-0.0434107,-0.474518
66,3.0,uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0,-57.6967,95.481,147,236,383,-0.392495,0.404581,0.00604298,-0.259649
39,4.0,lincoln square,3.4,10.9,8.2,13.4,25.5,37524,17.0,-2.3563,88.356,7,157,164,-0.336614,0.562777,0.113081,-0.186716
51,5.0,north center,0.3,7.5,5.2,4.5,26.2,57123,6.0,-10.4607,18.5448,21,40,61,-0.498129,0.46362,-0.0172543,-0.337837
37,6.0,lake view,1.1,11.4,4.7,2.6,17.0,60058,5.0,-6.675,16.2563,15,28,43,-0.445,0.580582,0.0677911,-0.27407
38,7.0,lincoln park,0.8,12.3,5.1,3.6,21.5,71551,2.0,-94.7576,310.297,182,582,764,-0.520646,0.533156,0.0062551,-0.345012
47,8.0,near north side,1.9,12.9,7.0,2.5,22.6,88669,1.0,-0.802,7.8572,1,16,17,-0.802,0.491075,-0.155463,-0.586487
22,9.0,edison park,1.1,3.3,6.5,7.4,35.3,40959,8.0,-0.5958,8.7805,2,17,19,-0.2979,0.5165,0.1093,-0.162167
54,10.0,norwood park,2.0,5.4,9.0,11.5,39.5,32875,21.0,-7.7546,4.1417,21,7,28,-0.369267,0.591671,0.111202,-0.20911
35,11.0,jefferson park,2.7,8.6,12.4,13.4,35.5,27751,25.0,-24.5815,10.493,49,20,69,-0.501663,0.52465,0.0114934,-0.330611
24,12.0,forest glen,1.1,7.5,6.8,4.9,40.5,44164,11.0,-0.5574,0.9058,1,1,2,-0.5574,0.9058,0.1742,-0.313533
53,13.0,north park,3.9,13.2,9.9,14.4,39.0,26576,33.0,-14.5291,38.2856,36,74,110,-0.403586,0.517373,0.0568934,-0.250093
0,14.0,albany park,11.3,19.2,10.0,32.9,32.0,21323,53.0,-5.6676,9.7646,16,18,34,-0.354225,0.542478,0.0941264,-0.204775
57,15.0,portage park,4.1,11.6,12.6,19.3,34.0,24336,35.0,-10.4311,15.3506,19,25,44,-0.549005,0.614024,0.0325094,-0.355167
34,16.0,irving park,6.3,13.1,10.0,22.4,31.6,27249,34.0,-8.3567,9.9079,23,21,44,-0.363335,0.471805,0.054235,-0.224145
18,17.0,dunning,5.2,10.6,10.0,16.2,33.6,26282,28.0,-8.8078,22.1743,21,65,86,-0.419419,0.341143,-0.039138,-0.292659
44,18.0,montclaire,8.1,15.3,13.8,23.5,38.6,22014,50.0,0,0,0,0,0,0,0,0,0
8,19.0,belmont cragin,10.8,18.7,14.6,37.3,37.3,15461,70.0,0,0,0,0,0,0,0,0,0
31,20.0,hermosa,6.9,20.5,13.1,41.6,36.4,15089,71.0,-10.6583,24.3991,22,58,80,-0.484468,0.420674,-0.031897,-0.333611
7,21.0,avondale,6.0,15.3,9.2,24.7,31.0,20039,42.0,-7.2062,7.627,18,15,33,-0.400344,0.508467,0.0540611,-0.248876
40,22.0,logan square,3.2,16.8,8.2,14.8,26.2,31908,23.0,-24.9594,74.0059,60,161,221,-0.41599,0.459664,0.021837,-0.270048
32,23.0,humboldt park,14.8,33.9,17.3,35.4,38.0,13781,85.0,-27.2708,22.3413,126,45,171,-0.216435,0.496473,0.140019,-0.0976169
75,24.0,west town,2.3,14.7,6.6,12.9,21.7,43198,10.0,-2.3882,25.6804,4,50,54,-0.59705,0.513608,-0.041721,-0.41194
5,25.0,austin,6.3,28.6,22.6,24.4,37.9,15957,73.0,-14.1287,18.5554,34,36,70,-0.41555,0.515428,0.0499389,-0.260387
71,26.0,west garfield park,9.4,41.7,25.8,24.5,43.6,10934,92.0,-5.0693,4.6487,7,8,15,-0.724186,0.581088,-0.0715491,-0.50664
19,27.0,east garfield park,8.2,42.4,19.6,21.3,43.2,12961,83.0,-159.653,5.5437,287,11,298,-0.556282,0.503973,-0.0261544,-0.379572
49,28.0,near west side,3.8,20.6,10.7,9.6,22.2,44689,15.0,-4.9914,12.8581,19,29,48,-0.262705,0.443383,0.0903387,-0.145024
52,29.0,north lawndale,7.4,43.1,21.2,27.6,42.7,12034,87.0,-54.1112,57.0527,112,101,213,-0.483136,0.564878,0.0408713,-0.308467
64,30.0,south lawndale,15.2,30.7,15.8,54.8,33.8,10402,96.0,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,48.0,calumet heights,2.1,11.5,20.0,11.0,44.0,28887,38.0,NA,NA,NA,NA,NA,NA,NA,NA,NA
61,49.0,roseland,2.5,19.8,20.3,16.9,41.2,17949,52.0,-162.523,12.9962,315,30,345,-0.515947,0.433207,-0.0413703,-0.357755
58,50.0,pullman,1.5,21.6,22.8,13.1,38.6,20588,51.0,-6.3766,9.2418,14,17,31,-0.455471,0.543635,0.0440819,-0.288954
63,51.0,south deering,4.0,29.2,16.3,21.0,39.5,14685,65.0,0,0.5848,0,1,1,0,0.5848,0,0
20,52.0,east side,6.8,19.2,12.1,31.9,42.8,17104,64.0,-9.8968,23.0107,24,45,69,-0.412367,0.511349,0.0494911,-0.258414
73,53.0,west pullman,3.3,25.9,19.4,20.5,42.1,16563,62.0,-4.0916,3.1795,10,6,16,-0.40916,0.529917,0.0603783,-0.252647
59,54.0,riverdale,5.8,56.5,34.6,27.5,51.5,8201,98.0,-134.11,8.7716,210,20,230,-0.638618,0.43858,-0.100019,-0.459085
30,55.0,hegewisch,3.3,17.1,9.6,19.2,42.9,22677,44.0,0,0.5106,0,1,1,0,0.5106,0,0
27,56.0,garfield ridge,2.6,8.8,11.3,19.3,38.1,26353,32.0,-25.9085,2.9174,40,5,45,-0.647713,0.58348,-0.0321163,-0.442514
1,57.0,archer heights,8.5,14.1,16.5,35.9,39.2,16134,67.0,0,0.5574,0,1,1,0,0.5574,0,0
11,58.0,brighton park,14.4,23.6,13.9,45.1,39.3,13089,84.0,-0.5216,2.0169,1,3,4,-0.5216,0.6723,0.07535,-0.322617
43,59.0,mckinley park,7.2,18.7,13.4,32.9,35.6,16954,61.0,-0.5053,0.5106,1,1,2,-0.5053,0.5106,0.00265,-0.335983
10,60.0,bridgeport,4.5,18.9,13.7,22.2,31.3,22694,43.0,-16.1919,44.0589,36,87,123,-0.449775,0.506424,0.0283246,-0.290408
50,61.0,new city,11.9,29.0,23.0,41.5,38.9,12765,91.0,-68.2218,106.165,120,224,344,-0.568515,0.473951,-0.0472818,-0.394771
69,62.0,west elsdon,11.1,15.6,16.7,37.0,37.7,15754,69.0,NA,NA,NA,NA,NA,NA,NA,NA,NA
26,63.0,gage park,15.8,23.4,18.2,51.5,38.8,12171,93.0,-0.3818,2.5715,1,4,5,-0.3818,0.642875,0.130538,-0.211021
16,64.0,clearing,2.7,8.9,9.5,18.8,37.6,25113,29.0,-33.5426,61.5269,65,131,196,-0.51604,0.469671,-0.0231845,-0.351755
72,65.0,west lawn,5.8,14.9,9.6,33.6,39.6,16907,56.0,-1.682,1.225,6,4,10,-0.280333,0.30625,0.0129583,-0.182569
15,66.0,chicago lawn,7.6,27.9,17.1,31.2,40.6,13231,80.0,-7.2072,5.9058,12,19,31,-0.6006,0.310832,-0.144884,-0.448695
70,67.0,west englewood,4.8,34.4,35.9,26.3,40.7,11317,89.0,-18.0989,1.0187,32,2,34,-0.565591,0.50935,-0.0281203,-0.386434
23,68.0,englewood,3.8,46.6,28.0,28.5,42.5,11888,94.0,-178.218,119.305,362,238,600,-0.492316,0.501282,0.00448317,-0.326716
29,69.0,greater grand crossing,3.6,29.6,23.0,16.5,41.0,17285,66.0,0,8.16,0,12,12,0,0.68,0,0
3,70.0,ashburn,4.0,10.4,11.7,17.7,36.9,23482,37.0,-10.6303,5.5188,28,15,43,-0.379654,0.36792,-0.00586679,-0.255058
4,71.0,auburn gresham,4.0,27.6,28.3,18.5,41.9,15528,74.0,-5.9133,1.1233,17,2,19,-0.347841,0.56165,0.106904,-0.196259
9,72.0,beverly,0.9,5.1,8.0,3.7,40.5,39523,12.0,-35.3824,174.629,115,344,459,-0.307673,0.507642,0.0999844,-0.171787
67,73.0,washington height,1.1,16.9,20.8,13.7,42.6,19713,48.0,NA,NA,NA,NA,NA,NA,NA,NA,NA
46,74.0,mount greenwood,1.0,3.4,8.7,4.3,36.8,34381,16.0,-15.6672,6.5758,25,14,39,-0.626688,0.4697,-0.078494,-0.443957
45,75.0,morgan park,0.8,13.2,15.0,10.8,40.3,27149,30.0,-36.5963,108.69,103,200,303,-0.355304,0.543451,0.0940738,-0.205511
55,76.0,o'hare,3.6,15.4,7.1,10.9,30.3,25828,24.0,-0.4466,2.5444,1,5,6,-0.4466,0.50888,0.03114,-0.287353
21,77.0,edgewater,4.1,18.2,9.2,9.7,23.8,33385,19.0,-15.7117,37.0392,42,74,116,-0.374088,0.50053,0.0632208,-0.228318

In [60]:
# show me the neighborhoods that are not mentioned even once among the tweets downloaded for this round of analysis
df_merged[df_merged['Unweighted Reputation Score'] == 'NA']

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX,Sum Negative Tweet Sentiment,Sum Positive Tweet Sentiment,Total Number of Negative Tweets,Total Number of Positive Tweets,Total Number of Positive and Negative Tweets,Average Negative Sentiment,Average Positive Sentiment,Unweighted Reputation Score,Weighted Reputation Score
64,30.0,south lawndale,15.2,30.7,15.8,54.8,33.8,10402,96.0,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,34.0,armour square,5.7,40.1,16.7,34.5,38.3,16148,82.0,NA,NA,NA,NA,NA,NA,NA,NA,NA
13,48.0,calumet heights,2.1,11.5,20.0,11.0,44.0,28887,38.0,NA,NA,NA,NA,NA,NA,NA,NA,NA
69,62.0,west elsdon,11.1,15.6,16.7,37.0,37.7,15754,69.0,NA,NA,NA,NA,NA,NA,NA,NA,NA
67,73.0,washington height,1.1,16.9,20.8,13.7,42.6,19713,48.0,NA,NA,NA,NA,NA,NA,NA,NA,NA

In [61]:
df_merged.shape

(77, 18)

In [62]:
df_merged.to_csv('df_merged.csv')

# Develop descriptive statistics

In [63]:
import numpy as np
import matplotlib.pyplot as plt

In [75]:
df_neighb_level = pd.read_csv('df_merged.csv')
del df_neighb_level['Unnamed: 0']
#df_neighb_level
df_tweet_level = pd.read_csv('df_wCompound.csv')  # this contains all of the neutral tweets, remove this
del df_tweet_level['Unnamed: 0']
del df_tweet_level['Unnamed: 0.1']
#df_tweet_level

In [76]:
# remove all tweets that score neutral in terms of compound sentiment score
df_tweet_level = df_tweet_level[df_tweet_level['Compound Sentiment Score'] != 0]
#df_tweet_level[df_tweet_level['Compound Sentiment Score'] == 0]

In [77]:
print(df_tweet_level.columns)
print(df_neighb_level.columns)

Index(['Community Area Mentioned', 'Tweet Content', 'Tweet Coordinates',
       'Tweet Day and Time', 'Tweet Number of Times Liked',
       'Tweet Number of Times Retweeted', 'User Location',
       'User Number of Followers', 'User Screen Name', 'Sentiment',
       'Compound Sentiment Score'],
      dtype='object')
Index(['Community Area Number', 'COMMUNITY AREA NAME',
       'PERCENT OF HOUSING CROWDED', 'PERCENT HOUSEHOLDS BELOW POVERTY',
       'PERCENT AGED 16+ UNEMPLOYED',
       'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA',
       'PERCENT AGED UNDER 18 OR OVER 64', 'PER CAPITA INCOME ',
       'HARDSHIP INDEX', 'Sum Negative Tweet Sentiment',
       'Sum Positive Tweet Sentiment', 'Total Number of Negative Tweets',
       'Total Number of Positive Tweets',
       'Total Number of Positive and Negative Tweets',
       'Average Negative Sentiment', 'Average Positive Sentiment',
       'Unweighted Reputation Score', 'Weighted Reputation Score'],
      dtype='object')

In [80]:
# show basic descriptives stats per neighborhood and per variable 
a = df_tweet_level.groupby('Community Area Mentioned')
# can also use a.mean() and a.std() to examine just mean or standard deviation

b = df_neighb_level.groupby('COMMUNITY AREA NAME')
# b.mean() and b.std()

a.describe()
b.describe()

                                Compound Sentiment Score  \
Community Area Mentioned
albany park              count  34.000000
                         mean   0.120500
                         std    0.474977
                         min   -0.735100
                         25%   -0.340000
                         50%    0.283200
                         75%    0.560600
                         max    0.803400
archer heights           count  1.000000
                         mean   0.557400
                         std   NaN
                         min    0.557400
                         25%    0.557400
                         50%    0.557400
                         75%    0.557400
                         max    0.557400
ashburn                  count  43.000000
                         mean  -0.118872
                         std    0.404982
                         min   -0.952400
                         25%   -0.401900
                         50%   -0.273200
                         75%    0.222850
                         max    0.778300
auburn gresham           count  19.000000
                         mean  -0.252105
                         std    0.358420
                         min   -0.557400
                         25%   -0.557400
                         50%   -0.177900
...                                  ...
west pullman             std    0.475447
                         min   -0.612400
                         25%   -0.401900
                         50%   -0.401900
                         75%    0.487525
                         max    0.611400
west ridge               count  31.000000
                         mean   0.311210
                         std    0.571706
                         min   -0.812600
                         25%    0.361200
                         50%    0.585900
                         75%    0.636900
                         max    0.875000
west town                count  54.000000
                         mean   0.431337
                         std    0.346244
                         min   -0.765000
                         25%    0.401900
                         50%    0.458100
                         75%    0.628900
                         max    0.902200
woodlawn                 count  57.000000
                         mean   0.401949
                         std    0.385990
                         min   -0.439100
                         25%    0.318200
                         50%    0.440400
                         75%    0.765000
                         max    0.902000

                                Tweet Number of Times Liked  \
Community Area Mentioned
albany park              count  34.000000
                         mean   0.352941
                         std    0.645842
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    0.750000
                         max    2.000000
archer heights           count  1.000000
                         mean   1.000000
                         std   NaN
                         min    1.000000
                         25%    1.000000
                         50%    1.000000
                         75%    1.000000
                         max    1.000000
ashburn                  count  43.000000
                         mean   0.069767
                         std    0.457496
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    0.000000
                         max    3.000000
auburn gresham           count  19.000000
                         mean   0.473684
                         std    0.841191
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
...                                  ...
west pullman             std    0.250000
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    0.000000
                         max    1.000000
west ridge               count  31.000000
                         mean   0.870968
                         std    1.607108
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    1.000000
                         max    6.000000
west town                count  54.000000
                         mean   0.703704
                         std    2.507571
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    0.000000
                         max    14.000000
woodlawn                 count  57.000000
                         mean   0.824561
                         std    2.188630
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    0.000000
                         max    11.000000

                                Tweet Number of Times Retweeted  \
Community Area Mentioned
albany park              count  34.000000
                         mean   0.058824
                         std    0.342997
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    0.000000
                         max    2.000000
archer heights           count  1.000000
                         mean   0.000000
                         std   NaN
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    0.000000
                         max    0.000000
ashburn                  count  43.000000
                         mean   2608.837209
                         std    8445.663108
                         min    0.000000
                         25%    0.000000
                         50%    1.000000
                         75%    54.500000
                         max    35482.000000
auburn gresham           count  19.000000
                         mean   0.842105
                         std    1.258887
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
...                                  ...
west pullman             std    0.000000
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    0.000000
                         max    0.000000
west ridge               count  31.000000
                         mean   0.967742
                         std    1.016001
                         min    0.000000
                         25%    0.000000
                         50%    1.000000
                         75%    1.000000
                         max    3.000000
west town                count  54.000000
                         mean   1.314815
                         std    5.692842
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    0.000000
                         max    41.000000
woodlawn                 count  57.000000
                         mean   2.456140
                         std    6.892206
                         min    0.000000
                         25%    0.000000
                         50%    0.000000
                         75%    3.000000
                         max    51.000000

                                User Number of Followers
Community Area Mentioned
albany park              count  34.000000
                         mean   661.647059
                         std    873.805605
                         min    30.000000
                         25%    157.000000
                         50%    266.500000
                         75%    999.000000
                         max    4512.000000
archer heights           count  1.000000
                         mean   46.000000
                         std   NaN
                         min    46.000000
                         25%    46.000000
                         50%    46.000000
                         75%    46.000000
                         max    46.000000
ashburn                  count  43.000000
                         mean   3160.325581
                         std    11900.989814
                         min    51.000000
                         25%    114.500000
                         50%    787.000000
                         75%    1252.000000
                         max    76894.000000
auburn gresham           count  19.000000
                         mean   7515.315789
                         std    17464.502970
                         min    131.000000
                         25%    262.500000
                         50%    1743.000000
...                                    ...
west pullman             std    859.977713
                         min    52.000000
                         25%    186.250000
                         50%    229.000000
                         75%    1252.000000
                         max    2558.000000
west ridge               count  31.000000
                         mean   10051.612903
                         std    23796.145165
                         min    18.000000
                         25%    119.500000
                         50%    1197.000000
                         75%    4666.000000
                         max    87609.000000
west town                count  54.000000
                         mean   18415.351852
                         std    103103.425050
                         min    11.000000
                         25%    244.500000
                         50%    652.500000
                         75%    2652.500000
                         max    754571.000000
woodlawn                 count  57.000000
                         mean   3480.719298
                         std    3723.897117
                         min    16.000000
                         25%    391.000000
                         50%    1017.000000
                         75%    8563.000000
                         max    12343.000000

[544 rows x 4 columns]

# Develop inferential statistics

# Conclusions